version: "3.8" # Define la versión de Docker Compose

networks:
  app-network:
    driver: bridge

services:
  # Servicio del webserver (debe iniciar primero)
  webserver:
    build: ./rails-server
    container_name: ruby-server
    env_file:
      - ./rails-server/.env
    volumes:
      - ./rails-server:/app
    ports:
      - "8080:8080"
    networks:
      - app-network
    stdin_open: true
    tty: true
    environment:
      - WEMOS_IP=192.168.1.65
<<<<<<< HEAD
      - WEMOS_PORT=4040
=======
      - WEMOS_PORT=12345
>>>>>>> master
      - WHISPER_PORT=8082
      - WHISPER_URL=http://whisper:8082
      - UDP_SERVER_HOST=udp-server
      - UDP_SERVER_PORT=12345

  # Servicio del frontend (depende del webserver)
  frontend-dashboard:
    build:
      context: ./dashboard-pwa
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://webserver:8080"
        NEXT_PUBLIC_BACKEND_WEBSOCKET_URL: "ws://webserver:8080"
    container_name: frontend-dashboard
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://webserver:8080
      - NEXT_PUBLIC_BACKEND_WEBSOCKET_URL=ws://webserver:8080
    depends_on:
      - webserver

  udp-server:
    build: ./udp-server
    container_name: udp-server
    volumes:
      - ./udp-server:/app
    ports:
      - "12345:12345/udp"
    networks:
      - app-network
    stdin_open: true
    tty: true
    environment:
      - WEBSERVER_URL=http://webserver:8080
      - WEBSOCKET_URL=ws://webserver:8080
      - WEBSOCKET_PORT=8080
      - WEMOS_IP=192.168.1.65
<<<<<<< HEAD
      - WEMOS_PORT=4040
=======
      - WEMOS_PORT=12345
>>>>>>> master

  whisper:
    build: ./whisper-server
    container_name: whisper-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - WEBSERVER_URL=http://webserver:8080
      - WEBSOCKET_URL=ws://webserver:8080
      - WEBSOCKET_PORT=8080
<<<<<<< HEAD
      - WEMOS_IP=192.168.1.65
=======
      - WEMOS_IP=192.168.1.64
>>>>>>> master
      - WEMOS_PORT=4040
