version: "3.8" # Define la versión de Docker Compose

networks:
  app-network:
    driver: bridge

services:
  # Servicio de la dashboard
  frontend-dashboard:
    build:
      context: ./dashboard-pwa
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: "http://localhost:8080"
        NEXT_PUBLIC_BACKEND_WEBSOCKET_URL: "ws://localhost:8080"
    container_name: frontend-dashboard
    ports:
      - "3000:3000" # Puerto mapeado
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8080
      - NEXT_PUBLIC_BACKEND_WEBSOCKET_URL=ws://localhost:8080

  # Servicio de la aplicación web (ej. una app en Ruby)
  webserver:
    build: ./rails-server
    container_name: ruby-server
    env_file:
      - ./rails-server/.env
    volumes:
      - ./rails-server:/app
    ports:
      - "8080:8080"
    networks:
      - app-network
    stdin_open: true
    tty: true
    environment:
      - WEMOS_IP=192.168.1.64
      - WEMOS_PORT=4040
      - WHISPER_PORT=8082
      - WHISPER_URL=http://whisper:8082
      - UDP_SERVER_HOST=udp-server
      - UDP_SERVER_PORT=44444

  udp-server:
    build: ./udp-server
    container_name: udp-server
    volumes:
      - ./udp-server:/app
    ports:
      - "44444:44444/udp"
    networks:
      - app-network
    stdin_open: true
    tty: true
    environment:
      - WEBSERVER_URL=http://webserver:8080
      - WEBSOCKET_URL=ws://webserver:8080
      - WEBSOCKET_PORT=8080
      - WEMOS_IP=192.168.1.65
      - WEMOS_PORT=12345

  whisper:
    build: ./whisper-server
    container_name: whisper-service
    ports:
      - "8082:8082"
    networks:
      - app-network
    environment:
      - WEBSERVER_URL=http://webserver:8080
      - WEBSOCKET_URL=ws://webserver:8080
      - WEBSOCKET_PORT=8080
      - WEMOS_IP=192.168.1.64
      - WEMOS_PORT=4040
