version: '3.8'  # Define la versión de Docker Compose

services:
  # Servicio de la base de datos PostgreSQL
  frontend-dashboard:
    build: ./dashboard-pwa
    container_name: frontend-dashboard 
    ports:
      - "3000:3000" # Puerto mapeado

  # Servicio de la aplicación web (ej. una app en Node.js)
  webserver:
    build: ./rails-server # Imagen de Node.js
    container_name: ruby-server
    environment:
      SECRET_KEY_BASE: akjnajsdfkanskfskj
      RAILS_ENV: development
    ports:
      - "12345:12345"
      - "8080:8080"

  whisper:
    build: ./whisper-server
    container_name: whisper-service
    ports:
      - "8081:8081" 