# Usa una imagen base oficial de Python 3
FROM python:3.10.12

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requerimientos (dependencies) a la imagen del contenedor
COPY requirements.txt .

# Instalar las dependencias especificadas en el archivo requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación Flask al contenedor
COPY . .

# Exponer el puerto 5000 (puerto por defecto de Flask)
EXPOSE 8080

# Comando por defecto para ejecutar la aplicación usando gunicorn
CMD ["python3, app.py"]
